theme = "tokyonight_moon"

[editor]
line-number = "relative"
end-of-line-diagnostics = "hint"
scroll-lines = 1
cursorline = true
cursorcolumn = true
bufferline = "multiple"
color-modes = true
undercurl = true
mouse = false
true-color = true
indent-heuristic = "tree-sitter"
# original
# gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
gutters = ["diagnostics", "spacer", "diff", "line-numbers", "spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
wrap-indicator = "↩ "

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.statusline]
left = [
  "mode",
  "spacer",
  "version-control",
  "spacer",
  "separator",
  "file-name",
  "file-modification-indicator",
  "spacer",
  "read-only-indicator",
]
right = [
  "spinner",
  "spacer",
  "workspace-diagnostics",
  "separator",
  "spacer",
  "diagnostics",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]

separator = "│"
mode.normal = "normal"
mode.insert = "insert"
mode.select = "select"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.indent-guides]
render = true
character = "┆" # Characters options: "▏", "┆", "┊", "⸽" "╎"
skip-levels = 0

[editor.file-picker]
hidden = false

[keys.normal]
p = "paste_clipboard_before"
y = "yank_main_selection_to_clipboard"
C-r = ":config-reload"
esc = ["collapse_selection", "keep_primary_selection"]

# Mark line and move with them up/down
# https://github.com/helix-editor/helix/discussions/5764#discussioncomment-4840408
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]

[keys.normal.g]
"left" = "goto_line_start"
"right" = "goto_line_end"

[keys.insert]
"C-space" = "completion"
